name: 🚀 Laravel Auto Deploy

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy
      run: |
        ssh -o StrictHostKeyChecking=no -p 33310 root@38.46.220.50 << 'EOF'
          cd /home/expasign
          git pull 
          docker compose up --build -d
        EOF
