name: 🚀 Laravel Auto Deploy

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy
      run: |
        ssh -o StrictHostKeyChecking=no -p 33310 root@38.46.220.50 << 'EOF'
          set -e
          source ~/.bashrc
          cd /home/expasign
          git fetch origin
          git reset --hard origin/main
          /root/.nvm/versions/node/v22.14.0/bin/npm i
          /root/.nvm/versions/node/v22.14.0/bin/npm run build
          docker compose up -d --force-recreate app
        EOF
